CREATE TABLE tblAbsenceType (
    ID               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AbsenceTypeCode  VARCHAR(4) NOT NULL,
    Description      VARCHAR(60),
    Description2     VARCHAR(30),
    Remark           VARCHAR(30),
    Point            NUMERIC(2,0) NOT NULL,
    PaidSalary       NUMERIC(6,2),
    PaidLeave        NUMERIC(6,2),
    PaidMeal         NUMERIC(6,2),
    PaidTransport    NUMERIC(6,2),
    PaidIncentive    NUMERIC(6,2),
    EntryTimeInYN    SMALLINT NOT NULL,
    EntryTimeOutYN   SMALLINT NOT NULL,
    UserEdit         VARCHAR(10),
    DateTimeEdit     TIMESTAMP
);


INSERT INTO tblAbsenceType (
  AbsenceTypeCode, Description, Description2, Remark, Point,
  PaidSalary, PaidLeave, PaidMeal, PaidTransport,
  EntryTimeInYN, EntryTimeOutYN, UserEdit
) VALUES ('A', 'ALPA', '', '', 5, 0, 0, 0, 0, 3, 3, 'SAMPLE');

INSERT INTO tblAbsenceType (
  AbsenceTypeCode, Description, Description2, Remark, Point,
  PaidSalary, PaidLeave, PaidMeal, PaidTransport,
  EntryTimeInYN, EntryTimeOutYN, UserEdit
) VALUES ('CH', 'CUTI HAID', '', '', 0, 100, 0, 0, 0, 3, 3, 'SAMPLE');

INSERT INTO tblAbsenceType (
  AbsenceTypeCode, Description, Description2, Remark, Point,
  PaidSalary, PaidLeave, PaidMeal, PaidTransport,
  EntryTimeInYN, EntryTimeOutYN, UserEdit
) VALUES ('CM', 'CUTI MELAHIRKAN', '', '', 0, 100, 0, 0, 0, 3, 3, 'SAMPLE');

INSERT INTO tblAbsenceType (
  AbsenceTypeCode, Description, Description2, Remark, Point,
  PaidSalary, PaidLeave, PaidMeal, PaidTransport,
  EntryTimeInYN, EntryTimeOutYN, UserEdit
) VALUES ('CN', 'CUTI NIKAH', '', '', 0, 100, 0, 0, 0, 3, 3, 'SAMPLE');

INSERT INTO tblAbsenceType (
  AbsenceTypeCode, Description, Description2, Remark, Point,
  PaidSalary, PaidLeave, PaidMeal, PaidTransport,
  EntryTimeInYN, EntryTimeOutYN, UserEdit
) VALUES ('CT', 'CUTI TAHUNAN', '', '', 0, 100, 0, 0, 0, 3, 3, 'SAMPLE');

INSERT INTO tblAbsenceType (
  AbsenceTypeCode, Description, Description2, Remark, Point,
  PaidSalary, PaidLeave, PaidMeal, PaidTransport,
  EntryTimeInYN, EntryTimeOutYN, UserEdit
) VALUES ('DL', 'DINAS LUAR', '', '', 0, 100, 0, 100, 100, 3, 3, 'SAMPLE');

INSERT INTO tblAbsenceType (
  AbsenceTypeCode, Description, Description2, Remark, Point,
  PaidSalary, PaidLeave, PaidMeal, PaidTransport,
  EntryTimeInYN, EntryTimeOutYN, UserEdit
) VALUES ('I', 'IJIN/SAKIT', '', '', 1, 0, 0, 0, 0, 3, 3, 'SAMPLE');

INSERT INTO tblAbsenceType (
  AbsenceTypeCode, Description, Description2, Remark, Point,
  PaidSalary, PaidLeave, PaidMeal, PaidTransport,
  EntryTimeInYN, EntryTimeOutYN, UserEdit
) VALUES ('IB', 'IJIN/SAKIT (DIBAYAR)', '', '', 0, 100, 0, 0, 0, 3, 3, 'SAMPLE');

INSERT INTO tblAbsenceType (
  AbsenceTypeCode, Description, Description2, Remark, Point,
  PaidSalary, PaidLeave, PaidMeal, PaidTransport,
  EntryTimeInYN, EntryTimeOutYN, UserEdit
) VALUES ('N', 'NORMAL', '', '', 0, 100, 0, 100, 100, 3, 3, 'SAMPLE');

INSERT INTO tblAbsenceType (
  AbsenceTypeCode, Description, Description2, Remark, Point,
  PaidSalary, PaidLeave, PaidMeal, PaidTransport,
  EntryTimeInYN, EntryTimeOutYN, UserEdit
) VALUES ('SC', 'SCORSING', '', '', 2, 0, 0, 0, 0, 3, 3, 'SAMPLE');

INSERT INTO tblAbsenceType (
  AbsenceTypeCode, Description, Description2, Remark, Point,
  PaidSalary, PaidLeave, PaidMeal, PaidTransport,
  EntryTimeInYN, EntryTimeOutYN, UserEdit
) VALUES ('P', 'PULANG', '', '', 2, 11, 0, 11, 100, 3, 2, 'SAMPLE');

INSERT INTO tblAbsenceType (
  AbsenceTypeCode, Description, Description2, Remark, Point,
  PaidSalary, PaidLeave, PaidMeal, PaidTransport,
  EntryTimeInYN, EntryTimeOutYN, UserEdit
) VALUES ('PI', 'PULANG AWAL/I', '', '', 1, 11, 0, 11, 100, 3, 2, 'SAMPLE');

INSERT INTO tblAbsenceType (
  AbsenceTypeCode, Description, Description2, Remark, Point,
  PaidSalary, PaidLeave, PaidMeal, PaidTransport,
  EntryTimeInYN, EntryTimeOutYN, UserEdit
) VALUES ('PB', 'PULANG DIBAYAR', '', '', 0, 100, 0, 11, 100, 3, 2, 'SAMPLE');

INSERT INTO tblAbsenceType (
  AbsenceTypeCode, Description, Description2, Remark, Point,
  PaidSalary, PaidLeave, PaidMeal, PaidTransport,
  EntryTimeInYN, EntryTimeOutYN, UserEdit
) VALUES ('T', 'TERLAMBAT', '', '', 2, 11, 0, 11, 100, 2, 3, 'SAMPLE');

INSERT INTO tblAbsenceType (
  AbsenceTypeCode, Description, Description2, Remark, Point,
  PaidSalary, PaidLeave, PaidMeal, PaidTransport,
  EntryTimeInYN, EntryTimeOutYN, UserEdit
) VALUES ('TB', 'TERLAMBAT (DIBAYAR)', '', '', 0, 100, 0, 100, 100, 2, 3, 'SAMPLE');

